#!/bin/bash

#### Установка Arch Gnome ####

### Подготовка ###

# Скачиваем образ Manjaro Minimal для установки Manjaro или Archlinux - https://manjaro.org/downloads/official/xfce/
# Или скачиваем образ EndeavourOS для установки только Archlinux - https://endeavouros.com/latest-release/
# Записываем образ на флешку, например програмой Ventoy - https://github.com/ventoy/Ventoy/releases
# Загружаемся с записанного образа,

# Запускаем эмулятор терминала.
# Переходим в учётную запись рута:
sudo su

# ***

## Только для установки Arch ##

# Пропишем в конфиги Pacman'а репозитории Archlinux и русские зеркала:
# (Для других стран можно сгенерировать тут: https://archlinux.org/mirrorlist/)
echo -e '[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 10
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist' > /etc/pacman.conf
echo -e '## Russia
Server = http://mirror.yandex.ru/archlinux/$repo/os/$arch
Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
Server = http://mirror.truenetwork.ru/archlinux/$repo/os/$arch
Server = https://mirror.truenetwork.ru/archlinux/$repo/os/$arch
Server = http://mirror.rol.ru/archlinux/$repo/os/$arch
Server = https://mirror.rol.ru/archlinux/$repo/os/$arch
Server = http://mirror.surf/archlinux/$repo/os/$arch
Server = https://mirror.surf/archlinux/$repo/os/$arch
Server = http://mirror.nw-sys.ru/archlinux/$repo/os/$arch
Server = https://mirror.nw-sys.ru/archlinux/$repo/os/$arch
Server = http://mirrors.powernet.com.ru/archlinux/$repo/os/$arch
Server = http://archlinux.zepto.cloud/$repo/os/$arch' > /etc/pacman.d/mirrorlist
pacman --noconfirm -Syy

# ***

## Только для установки Manjaro ##

# Настроим Pacman, пропишем вручную региональные зеркала репозитория и перечитаем репозитории:
sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 10/g' /etc/pacman.conf
echo -e '## Russia
Server = https://mirror.yandex.ru/mirrors/manjaro/stable/$repo/$arch
Server = https://mirror.truenetwork.ru/manjaro/stable/$repo/$arch' | tee /etc/pacman.d/mirrorlist
pacman --noconfirm -Syy

#-----------------------------------------------------------------

### Установка ###
# Разметка, форматирование диска и установка базовой системы.
# Внимание!!! Запускаем только один из двух скриптов, в зависимости от устанавливаемой файловой системы:

## Btrfs ##
# Внимание!!! Все данные с указанного диска будут СТЁРТЫ!!!
# Для UEFI скрипт создаёт два раздела: основной с тремя подтомами @root, @home, @snapshot и boot/efi
# Для BIOS скрипт создаёт один основной раздел с тремя подтомами @root, @home и @snapshot
# Передаваемые скрипту параметры:
# 1й - файловая система (возможны 2 параметра: btrfs или ext4)
# 2й - имя диска,
# 3й - размер файла подкачки в мегабайтах (8192 = 8х1024 = 8Gb), 0 - не создавать,
# 4й - устанавливаемое ядро (linux-lts - LTS-ядро, linux - Последняя стабильная версия),
# 5й - размер boot/efi-раздела,
# 6й - размер root-раздела для ext4 (под раздел home - всё остальное пространство).
wget -c "https://raw.githubusercontent.com/S0u1b0y/install/Instructions/arch-base"
sh arch-base btrfs /dev/sda linux 8192 300M

## Ext4 ##
# Внимание!!! Все данные с указанного диска будут СТЁРТЫ!!!
# Для UEFI скрипт создаёт три раздела: root, home и boot/efi
# Для BIOS скрипт создаёт два раздела: root, home
# Передаваемые скрипту параметры смотри в описании btrfs
wget -c "https://raw.githubusercontent.com/S0u1b0y/install/Instructions/arch-base"
sh arch-base ext4 /dev/sda linux 8192 300M 40G

#-----------------------------------------------------------------

## Чрутимся:
# Если ставим из Manjaro
manjaro-chroot /mnt
# Если ставим из Endeavour или Arch
arch-chroot /mnt

#-----------------------------------------------------------------

## Установка основной системы ##

# Передаваемые скрипту параметры:
# 1й - имя пользователя
# 2й - имя компьютера в сети
# 3й - часовой пояс.
cd /tmp
wget -c "https://raw.githubusercontent.com/S0u1b0y/install/Instructions/arch-system"
sh arch-system user virt Europe/Moscow

#-----------------------------------------------------------------

#Если, на компьютере, есть MS Windows, то установим локальное время:
hwclock --systohc --localtime && date

#Если, на компьютере, только GNU/Linux, то установим время по UTC:
hwclock --systohc --utc && date

#-----------------------------------------------------------------

## Zswap - подкачка в оперативной памяти (Опционально) ##

# Устанавливаем (строка 1)
# Раскоментируем параметры в файле конфигурации (строка 2)
# Включим использование (строка 3)
# Отведем для zswap, вместо четверти, половину оперативной памяти (строка 4)
# Включаем загрузку при старте системы (строка 5)
sudo pacman --noconfirm -S systemd-swap
sudo sed -i 's/#zram_/zram_/g' /etc/systemd/swap.conf
sudo sed -i 's/zram_enabled=0/zram_enabled=1/' /etc/systemd/swap.conf
sudo sed -i 's/RAM_SIZE \/ 4/RAM_SIZE \/ 2/' /etc/systemd/swap.conf
sudo systemctl enable --now systemd-swap.service

#-----------------------------------------------------------------

## Статический IP (Опционально) ##

# Данные (netface, ipaddr, gateway) поменяйте на свои (строки 1-3),
# Имя сетевого интерфейса (переменная netface) можно узнать можно командой - ip a
# Делаем резервную копию файла настроек, на всякий случай (строка 4),
# Прописываем, в файл конфигурации, параметры настройки сети (строки 5-8),
netface=enp0s3
ipaddr=192.168.0.50
gateway=192.168.0.100
cp /etc/dhcpcd.conf /etc/dhcpcd.conf.bak
echo -e "interface $netface" > /etc/dhcpcd.conf
echo -e "static ip_address=$ipaddr/24" >> /etc/dhcpcd.conf
echo -e "static routers=$gateway" >> /etc/dhcpcd.conf
echo -e "static domain_name_servers=$gateway" >> /etc/dhcpcd.conf

#-----------------------------------------------------------------

## Драйвера для ноутбука ##

# Драйвер тачпада:
pacman --noconfirm -S xf86-input-synaptics

# Управление гибридной графикой Optimus Manager:
yay -S optimus-manager optimus-manager-qt
sudo systemctl enable optimus-manager

#-----------------------------------------------------------------

## Установка Gnome ##

# gnome-shell-performance - Минимальная установка Gnome,
# gdm - Загрузчик,
# gnome-control-center - Панель настроек Gnome,
# gnome-tweak-tool - Дополнительные настройки Gnome,
# tilix - Тайлинговый эмулятор терминала,
# gedit - Простой текстовый редактор,
# nautilus - Файловый менеджер,
# eog - Просмотр фото,
# evince - Просмотр документов,
# foliate - Читалка книг,
# file-roller - Работа с архивами,
# gnome-calculator - Калькулятор,
# caffeine-ng - Предотвращение активации экранной заставки,
# gnome-disk-utility - Управление дисками,
# gnome-system-monitor - Мониторинг системы,
# Удаление cheese - Приложение для веб-камеры.
sudo pacman --noconfirm -S gnome-shell gdm gnome-control-center gnome-tweak-tool tilix \
    gedit nautilus caffeine-ng gnome-disk-utility
sudo systemctl enable gdm.service
sudo pacman --noconfirm -R cheese

#-----------------------------------------------------------------

# Завершаем установку, выходим (Ctrl+D) и перезагружаемся:
reboot

#-----------------------------------------------------------------
#-----------------------------------------------------------------

#### После перезагрузки ####

# Автозагрузка GDM:
echo -e "[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=${USER}" | sudo tee -a /etc/gdm/custom.conf

## Tilix для Bash ##
echo -e '\n#Для терминала Tilix
if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi' >> ~/.bashrc
source ~/.bashrc

# Создаем каталоги пользователя в домашней папке на английском языке:
sudo pacman --noconfirm -S xdg-user-dirs && LC_ALL=C xdg-user-dirs-update --force
# То же самое, но на русском языке:
sudo pacman --noconfirm -S xdg-user-dirs && xdg-user-dirs-update --force

# ***

## Только для Arch ##

# Установим менеджер пакетов yay:
cd /tmp && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg --noconfirm -si

# Дополнительные утилиты, шрифты, иконки и курсоры:
yay --noconfirm -S pamac-aur papirus-icon-theme qogir-icon-theme ttf-meslo-nerd-font-powerlevel10k

# Расширения Gnome (Temporary outdated):
yay --noconfirm -S gnome-shell-extensions \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-gnome-ui-tune-git \
    gnome-shell-extension-vertical-overview-git \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-dash-to-panel \
    gnome-shell-extension-desktop-icons-ng \
    gnome-shell-extension-material-shell \
    gnome-shell-extension-pop-shell-bin \
    gnome-shell-extension-unite \
    gnome-shell-extension-gamemode-git \
gnome-shell-extension-gsconnect

# ***

## Только для Manjaro ##

# Программы Manjaro:
sudo pacman --noconfirm -S manjaro-settings-manager manjaro-browser-settings manjaro-hotfixes \
    pamac-gtk pamac-snap-plugin pamac-flatpak-plugin pamac-gnome-integration
# Оформление Manjaro:
sudo pacman --noconfirm -S papirus-maia-icon-theme matcha-gtk-theme adwaita-icon-theme \
    adwaita-maia manjaro-gdm-theme illyria-wallpaper

# Дополнительные утилиты, шрифты, иконки и курсоры:
yay --noconfirm -S yay qogir-icon-theme ttf-meslo-nerd-font-powerlevel10k

# Расширения оболочки Gnome и переключатель внешнего вида рабочего стола:
sudo pacman --noconfirm -S gnome-layout-switcher \
    gnome-shell-extensions \
    gnome-shell-extension-gnome-ui-tune \
    gnome-shell-extension-vertical-overview \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-arcmenu \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-dash-to-panel \
    gnome-shell-extension-desktop-icons-ng \
    gnome-shell-extension-material-shell \
    gnome-shell-extension-pop-shell \
    gnome-shell-extension-unite \
    gnome-shell-extension-gamemode \
gnome-shell-extension-gsconnect

# ***

# Дополнительные программы (Опционально):
# eog - Просмотр фото,
# evince - Просмотр документов,
# foliate - Читалка книг,
# file-roller - Работа с архивами,
# gnome-calculator - Калькулятор.
sudo pacman --noconfirm -S eog evince foliate file-roller gnome-calculator

# Оформление QT5 в стиле GTK:
yay --noconfirm -S qt5ct qt6-base adwaita-qt
echo 'export QT_QPA_PLATFORMTHEME=qt5ct' | sudo tee -a /etc/profile

#-----------------------------------------------------------------

### Настройки ###

# Установку и настройку Zsh см. в файле https://raw.githubusercontent.com/S0u1b0y/install/Instructions/arch-zsh

# Установим более низкий уровень использования файла подкачки (строка 1),
# Уменьшим время ожидания "зависших" приложений с 90 до 10 секунд (строка 2),
# Зададим максимальный размер systemd-журнала (строка 3).
echo 'vm.swappiness=10' | sudo tee /etc/sysctl.d/99-swappiness.conf
sudo sed -i 's/#DefaultTimeoutStopSec=90s/DefaultTimeoutStopSec=10s/' /etc/systemd/system.conf
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=50M/' /etc/systemd/journald.conf

# ***

## GRUB (Опционально) ##

# Если есть ещё установленные системы, то ставим дополнительно:
sudo pacman --noconfirm -S os-prober
# И перегенерируем файл конфигурации grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

# Если нет других установленных систем, то убираем загрузочное меню Grub,
# меняя GRUB_TIMEOUT с пяти секунд на ноль.
sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
# И перегенерируем файл конфигурации grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

#-----------------------------------------------------------------

## Программы ##

# Ananicy - Управляет приоритетами приложений:
yay --noconfirm -S ananicy && sudo systemctl enable --now ananicy

# Nohang - Следит за потреблением озу, выгружая неиспользуемые процессы:
yay --noconfirm -S nohang && sudo systemctl enable --now nohang

# Браузеры:
# Firefox
sudo pacman --noconfirm -S firefox firefox-i18n-ru
# LibreWolf
yay --noconfirm -S librewolf-bin
# Chrome:
yay --noconfirm -S google-chrome
# Chromium
sudo pacman --noconfirm -S chromium

# Bluetooth (опционально):
sudo pacman --noconfirm -S blueman
sudo systemctl enable --now bluetooth

# Управление сетевыми соединениями (опционально):
sudo pacman --noconfirm -S networkmanager plasma-nm
sudo systemctl enable --now NetworkManager
# Плагины NetworkManager для разных типов соединений (опционально):
sudo pacman --noconfirm -S networkmanager-openconnect networkmanager-openvpn networkmanager-pptp networkmanager-vpnc

# Если нужна поддержка принтера, то ставим:
pacman --noconfirm -S cups cups-pdf system-config-printer
sudo systemctl enable --now cups.service

# Torrent:
sudo pacman --noconfirm -S qbittorrent

# Java:
sudo pacman --noconfirm -S jre-openjdk

# Code OSS (free Visual Studio Code):
yay -S code
# Мои настройки (опционально):
mouseWheelScrollSensitivity - 2
editor.renderWhitespace - none
editor.wordWrap - On
editor.fontSize - 12
editor.dragAndDrop - false
# Сменить язык на русский
Ctrl-Shift-P -> Configure Display Language -> Меняем на Русский

# Работа с видео:
yay -S mediainfo mkvtoolnix-gui

# Мониторинг и разгон для nVidia карт Green With Envy (опционально):
yay --noconfirm -S gwe

# Yandex Disk:
yay --noconfirm -S yandex-disk && yandex-disk setup

# gnome-system-monitor - Мониторинг системы.
yay --noconfirm -S gnome-system-monitor

#-----------------------------------------------------------------

## Игры ##

# Steam:
sudo pacman --noconfirm -S steam

# PortProton (https://portwine-linux.ru/port-proton-linux):
sudo pacman -S gamemode lib32-gamemode icoutils zenity bubblewrap zstd cabextract tar
wget -c "https://github.com/Castro-Fidel/PortWINE/raw/master/portwine_install_script/PortProton-97"
sh PortProton-97

# Настройка Proton в Steam-клиенте на Linux: В меню (вверху слева) нажимаем: Steam->Настройки,
# выбираем раздел Steam Play (в самом низу) и там ставим галочку "Включить Steam Play для других продуктов",
# жмем ОК. Все Proton включён, можно пытаться запускать Windows-игры.

# Minecraft:
yay -S multimc jre8-openjdk
sudo archlinux-java set java-17-openjdk
java -version

#-----------------------------------------------------------------

## Виртуализация (опционально) ##

# VirtualBox стандартное ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-modules-arch
# VirtualBox LTS-ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-dkms

# KVM (Qemu):
sudo pacman -S virt-manager bridge-utils dnsmasq dmidecode ebtables iptables openbsd-netcat qemu qemu-arch-extra qemu-guest-agent ovmf vde2
sudo systemctl enable --now libvirtd dnsmasq
sudo gpasswd -a $(whoami) kvm libvirt && newgrp libvirt
sudo sed -i 's/#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/' /etc/libvirt/libvirtd.conf
sudo sed -i 's/#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/' /etc/libvirt/libvirtd.conf
sudo systemctl restart libvirtd.service
