#!/bin/bash

# Приём входных данных и запись их в переменные для дальнейшей установки:
os=$1

# Сделаем резевные копии на всякий случай.
cp /etc/pacman.conf /etc/pacman.conf.bak
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

# Прописываем конфиги Pacman в зависимости от устанавливаемой оси:
if [ $os = archlinux ]; then
    # Пропишем репозитории Archlinux и русские зеркала:
    # Для других стран можно сгенерировать тут: https://archlinux.org/mirrorlist/
    echo -e '[options]
    HoldPkg = pacman glibc
    Architecture = auto
    Color
    CheckSpace
    ParallelDownloads = 10
    SigLevel = Required DatabaseOptional
    LocalFileSigLevel = Optional
    [core]
    Include = /etc/pacman.d/mirrorlist
    [extra]
    Include = /etc/pacman.d/mirrorlist
    [community]
    Include = /etc/pacman.d/mirrorlist
    [multilib]
    Include = /etc/pacman.d/mirrorlist' > /etc/pacman.conf
    echo -e '## Russia
    Server = http://mirror.yandex.ru/archlinux/$repo/os/$arch
    Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
    Server = http://mirror.truenetwork.ru/archlinux/$repo/os/$arch
    Server = https://mirror.truenetwork.ru/archlinux/$repo/os/$arch
    Server = http://mirror.rol.ru/archlinux/$repo/os/$arch
    Server = https://mirror.rol.ru/archlinux/$repo/os/$arch
    Server = http://mirror.surf/archlinux/$repo/os/$arch
    Server = https://mirror.surf/archlinux/$repo/os/$arch
    Server = http://mirror.nw-sys.ru/archlinux/$repo/os/$arch
    Server = https://mirror.nw-sys.ru/archlinux/$repo/os/$arch
    Server = http://mirrors.powernet.com.ru/archlinux/$repo/os/$arch
    Server = http://archlinux.zepto.cloud/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    pacman --noconfirm -Syy

elif [ $os = manjaro ]; then
    # Настроим Pacman, пропишем вручную региональные зеркала репозитория и перечитаем репозитории:
    sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 10/g' /etc/pacman.conf
    echo -e '## Russia
    Server = https://mirror.yandex.ru/mirrors/manjaro/stable/$repo/$arch
    Server = https://mirror.truenetwork.ru/manjaro/stable/$repo/$arch' > /etc/pacman.d/mirrorlist
    pacman --noconfirm -Syy
fi
