#!/bin/bash

# Приём входных данных и запись их в переменные для дальнейшей установки:
os=$1
country=$2

# Сделаем резевные копии на всякий случай.
cp -n /etc/pacman.conf /etc/pacman.conf.bak
cp -n /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

# Прописываем конфиги Pacman в зависимости от устанавливаемой оси:
if [ $os = archlinux ]; then
# Пропишем репозитории Archlinux и русские зеркала:
# Для других стран можно сгенерировать тут: https://archlinux.org/mirrorlist/
echo -e '[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 10
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist' > /etc/pacman.conf
if [ $country = ru ]; then
echo -e '## Russia
Server = https://mirror.yandex.ru/archlinux/$repo/os/$arch
Server = https://mirror.truenetwork.ru/archlinux/$repo/os/$arch
Server = https://mirror.rol.ru/archlinux/$repo/os/$arch
Server = https://mirror.nw-sys.ru/archlinux/$repo/os/$arc
Server = https://mirror.surf/archlinux/$repo/os/$arch
## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = ua ]; then
echo -e '## Ukraine
Server = https://archlinux.astra.in.ua/$repo/os/$arch
Server = https://repo.endpoint.ml/archlinux/$repo/os/$arch
Server = https://archlinux.ip-connect.vn.ua/$repo/os/$arch
Server = https://mirror.mirohost.net/archlinux/$repo/os/$arch
Server = https://mirrors.nix.org.ua/linux/archlinux/$repo/os/$arch
## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = by ]; then
echo -e '## Belarus
Server = http://ftp.byfly.by/pub/archlinux/$repo/os/$arch
Server = http://mirror.datacenter.by/pub/archlinux/$repo/os/$arch
## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = kz ]; then
echo -e '## Kazakhstan
Server = https://mirror.hoster.kz/archlinux/$repo/os/$arch
Server = https://mirror.ps.kz/archlinux/$repo/os/$arch
## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = * ]; then
echo -e '## Worldwide
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
fi
pacman --noconfirm -Syy

elif [ $os = manjaro ]; then
# Пропишем репозитории Manjaro и русские зеркала:
echo -e '[options]
CacheDir = /var/cache/pacman/pkg/
HoldPkg      = pacman glibc manjaro-system
SyncFirst    = manjaro-system archlinux-keyring manjaro-keyring
Architecture = auto
Color
CheckSpace
ParallelDownloads = 10
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
[core]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
[extra]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
[community]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist' > /etc/pacman.conf
echo -e '## Global
Server = https://mirrors.fossho.st/manjaro/stable/$repo/$arch
Server = https://mirrors.manjaro.org/repo/stable/$repo/$arch' > /etc/pacman.d/mirrorlist
if [ $country = ru ]; then
echo -e '## Russia
Server = https://mirror.yandex.ru/mirrors/manjaro/stable/$repo/$arch
Server = https://mirror.truenetwork.ru/manjaro/stable/$repo/$arch
## Global
Server = https://mirrors.fossho.st/manjaro/stable/$repo/$arch
Server = https://mirrors.manjaro.org/repo/stable/$repo/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = ua ]; then
echo -e '## Ukraine
Server = https://fastmirror.pp.ua/manjaro/stable/$repo/$arch
## Global
Server = https://mirrors.fossho.st/manjaro/stable/$repo/$arch
Server = https://mirrors.manjaro.org/repo/stable/$repo/$arch' > /etc/pacman.d/mirrorlist
elif [ $country = by ]; then
echo -e '## Belarus
Server = http://mirror.datacenter.by/pub/mirrors/manjaro/stable/$repo/$arch
## Global
Server = https://mirrors.fossho.st/manjaro/stable/$repo/$arch
Server = https://mirrors.manjaro.org/repo/stable/$repo/$arch' > /etc/pacman.d/mirrorlist
fi
pacman --noconfirm -Syy
fi
