#!/bin/bash

## ZSH ##
# https://wiki.archlinux.org/title/zsh

# Если не установлена, то ставим ZSH и шрифт для неё:
yay --noconfirm -S ttf-meslo-nerd-font-powerlevel10k zsh

# Дополнительные шрифты:
yay --noconfirm -S nerd-fonts-ubuntu-mono nerd-fonts-hack

#-----------------------------------------------------------------

# Меняем командную оболочку на ZSH для пользователя и идём в домашнюю папку:
chsh -s $(which zsh) ${USER} && cd

# Устанавливаем фреймворк "Oh My Zsh":
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Устанавливаем плагины и тему powerlevel10k для пользователя:
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions $ZSH_CUSTOM/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

# Меняем конфиг zsh:
cp -n /home/${USER}/.zshrc /home/${USER}/.zshrc.bak
echo -e 'export ZSH="/home/${USER}/.oh-my-zsh"
\nDISABLE_MAGIC_FUNCTIONS="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
POWERLEVEL9K_INSTANT_PROMPT=quiet
\nZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git docker sudo extract zsh-syntax-highlighting zsh-completions zsh-autosuggestions)
\nsource $ZSH/oh-my-zsh.sh' | tee /home/${USER}/.zshrc > /dev/null
source /home/${USER}/.zshrc

# Сконфигурируем тему
p10k configure # {Y,Y,Y,Y - 3,1,2 - 1,1,1 - 2,3,4,4 - 1,2,1 - Y,1,Y}

#-----------------------------------------------------------------

# Переходим под рут:
sudo -s

# Меняем командную оболочку на ZSH для рута и идём в домашнюю папку:
chsh -s $(which zsh) root && cd

# Устанавливаем фреймворк "Oh My Zsh":
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Устанавливаем плагины и тему powerlevel10k для рута:
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions $ZSH_CUSTOM/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k

# Меняем конфиг zsh:
cp -n /root/.zshrc /root/.zshrc.bak
echo -e 'export ZSH="/root/.oh-my-zsh"
\nDISABLE_MAGIC_FUNCTIONS="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
POWERLEVEL9K_INSTANT_PROMPT=quiet
\nZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git docker sudo extract zsh-syntax-highlighting zsh-completions zsh-autosuggestions)
\nsource $ZSH/oh-my-zsh.sh' | tee /root/.zshrc > /dev/null
source /root/.zshrc

# Сконфигурируем тему
p10k configure # {Y,Y,Y,Y - 3,1,2 - 1,1,1 - 2,3,4,4 - 1,2,1 - Y,1,Y}

# Выходим из рут
exit
exit

#-----------------------------------------------------------------

## Настроим тему (необязательно) ##

cp /home/${USER}/.p10k.zsh /home/${USER}/.p10k.zsh.bak
sudo cp /root/.p10k.zsh /root/.p10k.zsh.bak
echo -e '
############ POWERLEVEL THEME SETTINGS ##############

POWERLEVEL9K_OS_ICON_BACKGROUND=white
POWERLEVEL9K_OS_ICON_FOREGROUND=blue

POWERLEVEL9K_USER_DEFAULT_BACKGROUND=240
POWERLEVEL9K_USER_DEFAULT_FOREGROUND=white
POWERLEVEL9K_USER_ROOT_BACKGROUND=009
POWERLEVEL9K_USER_ROOT_FOREGROUND=black

POWERLEVEL9K_HOST_REMOTE_BACKGROUND=red
POWERLEVEL9K_HOST_REMOTE_FOREGROUND=black
POWERLEVEL9K_HOST_LOCAL_BACKGROUND=011
POWERLEVEL9K_HOST_LOCAL_FOREGROUND=black

############ END OF POWERLEVEL THEME SETTINGS ##############' | sudo tee -a /home/${USER}/.p10k.zsh /root/.p10k.zsh > /dev/null
sed -i 's/# os identifier/# os identifier\n    user\t\t    # username\n    host\t\t    # hostname/' /home/${USER}/.p10k.zsh
sudo sed -i 's/# os identifier/# os identifier\n    user\t\t    # username\n    host\t\t    # hostname/' /root/.p10k.zsh
sed -i 's/ context/ # context/' /home/${USER}/.p10k.zsh
sudo sed -i 's/ context/ # context/' /root/.p10k.zsh
source /home/${USER}/.p10k.zsh

#-----------------------------------------------------------------

## Tilix для XFCE и Gnome ##

echo -e '\n#Для терминала Tilix
if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi' | sudo tee -a /home/${USER}/.zshrc /root/.zshrc > /dev/null

#-----------------------------------------------------------------

## Алиасы ##

echo -e '
#### Aliases ####

# Удаление неиспользуемых пакетов (Если нечего удалять, вылезет "ошибка: аргумент "-" указан с пустым stdin", это нормально).
alias autoremove="sudo pacman --noconfirm -Qtdq | sudo pacman --noconfirm -Rns -"
alias фгещкуьщму="sudo pacman --noconfirm -Qtdq | sudo pacman --noconfirm -Rns -"

# Быстрая установка и удаление из под рута без подтверждения (spac - Sudo PACman):
alias spac="sudo pacman --noconfirm"

# Быстрое обновление (pup - Pacman UPdate)
alias pup="sudo pacman -Syu"
alias згз="sudo pacman -Syu"

# Пинг делает только 5 запросов.
alias ping="ping -c 5"' | sudo tee -a /home/${USER}/.zshrc /root/.zshrc > /dev/null

#-----------------------------------------------------------------
