#!/bin/bash

# Приём входных данных и запись их в переменные для дальнейшей установки:
# rootpart   - Размер рут раздела
# swapfile   - Размер файла подкачки
# kernel     - Версия ядра
# install    - Режим установки (normal с удаление всего содеримого диска или safe оставляет home нетронутым)
rootpart=$1
let swapfile="${2//G}*1024"
kernel=$3
installmode=$4

# Сквозные данные для передачи во второй скрипт:
# username - Имя пользователя
# hostname - Имя компьтера в сети
# deskenv - Окружение рабочего стола (Возможные варианты: xfce, plasma, gnome)
username=$5
hostname=$6
deskenv=$7

# Переменные:
defaulthook='HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)'
ext4hook='HOOKS=(base systemd autodetect modconf block filesystems keyboard fsck)'

#-----------------------------------------------------------------

## Определение оборудования, оси и др. ##

# Определение операционной системы из которой идёт установка:
if [[ $(cat /etc/*-release | grep -w NAME | cut -d= -f2 | tr -d '"') == 'Manjaro Linux' ]]; then
    os=Manjaro
else
    os=Archlinux
fi

# Определяем по видеокарте виртуальная машина или реальный компьютер:
if [[ $(LC_ALL=C lspci | grep -i '.* VGA .*') == *' VMware '* ]]; then
    computer=Virtual
else
    computer=Real
fi

#-----------------------------------------------------------------

# Если этот скрипт уже запускался, то остаются примонтированные диски и файл подкачки.
# Поэтому, отключаем файл подкачки ...
if [ -d /mnt/@swap/swapfile ]; then
    # созданный для btrfs ...
    swapoff /mnt/@swap/swapfile
elif [ -d /mnt/mnt/swapfile ]; then
    # или созданный для ext4 ...
    swapoff /mnt/mnt/swapfile
fi
# и отмонтируем все примонтированные диски.
umount -R /mnt

#-----------------------------------------------------------------

## Разбивка диска ##
# Для BIOS создаем два раздела Root и Home:
if $installmode = normal ; then
    parted -s /dev/sda mktable msdos \
        mkpart primary ext4 1M $rootpart \
        mkpart primary ext4 $rootpart 100% \
    set 1 boot on
    # Форматируем раздел Home в ext4:
    mkfs.ext4 -L Home /dev/sda2
fi
# Форматируем раздел Root в ext4:
mkfs.ext4 -L Root /dev/sda1
# Примонтируем раздел Root в /mnt:
mount /dev/sda1 /mnt
# Создаем каталог /mnt/home:
mkdir -p /mnt/home
# Примонтируем раздел Home в /mnt/home:
mount /dev/sda2 /mnt/home

#-----------------------------------------------------------------

# Ставим базовую систему:
# base, base-devel - Базовая система и пакеты для компиляции,
# $kernel $kernel\-headers - Ядро,
# nano - Простой консольный текстовый редактор,
# grub - загрузчик оси,
# intel-ucode - Микрокод для интела,
# zsh - Продвинутая командная оболочка.
if [ $os = Manjaro ]; then # Установка из Manjaro
    basestrap /mnt base base-devel $kernel $kernel\-headers nano grub intel-ucode zsh
    # На реальный компьютер ставим пакет драйверов linux-firmware, на виртуальном он не нужен.
    if [ $computer = Real ]; then
        basestrap /mnt linux-firmware
    fi
    # Генерируем fstab по UUID:
    fstabgen -U /mnt > /mnt/etc/fstab
else # Установка из Arch-подобных дистрибутивов (Archlinux, EndeavourOS и др.)
    pacstrap /mnt base base-devel $kernel $kernel\-headers nano grub intel-ucode zsh
    # На реальный компьютер ставим пакет драйверов linux-firmware, на виртуальном он не нужен.
    if [ $computer = Real ]; then
        pacstrap /mnt linux-firmware
    fi
    # Генерируем fstab по UUID:
    genfstab -U /mnt > /mnt/etc/fstab
fi

#-----------------------------------------------------------------

## Swapfile ##
# Переходим в mnt устанавливаемой системы
cd /mnt/mnt
# Создаём файл нужного размера
dd if=/dev/zero of=./swapfile bs=1M count=$swapfile status=progress
# Разрешаем доступ к файлу подкачки только root-у
chmod 600 ./swapfile
# Инициализируем файл подкачки и включаем его
mkswap ./swapfile
swapon ./swapfile
# Прописываем в fstab, автомонтирование файла подкачки при загрузке системы
echo -e '# Swapfile\n/mnt/swapfile none swap sw 0 0' | sudo tee -a /mnt/etc/fstab

#-----------------------------------------------------------------

# Настроим параметры запуска системы:
sed -i "s/^$defaulthook/$ext4hook/" /mnt/etc/mkinitcpio.conf

#-----------------------------------------------------------------

# Скопируем второй установочный скрипт в каталог /mnt, чтобы он был доступен из под chroot:
cp /arch-bios /mnt/arch-bios
# Продолжаем установку в chroot и отправляем туда второй скрипт:
if [ $os = Manjaro ]; then
    # Если ставим из Manjaro
    manjaro-chroot /mnt sh /arch-bios $username $hostname $deskenv
else
    # Если ставим из Arch
    arch-chroot /mnt sh /arch-bios $username $hostname $deskenv
fi
# После выхода из chroot удаляем скрипт, чтобы он не остался в установленной системе
rm /mnt/arch-bios
