#!/bin/bash

#### Установка Arch Gnome ####

### Подготовка ###

# Скачиваем образ Manjaro для установки Manjaro или Archlinux - https://manjaro.org/download/
# Или скачиваем образ EndeavourOS для установки только Archlinux - https://endeavouros.com/latest-release/
# Записываем образ на флешку програмой Ventoy - https://github.com/ventoy/Ventoy/releases
# Загружаемся с записанного образа
# Запускаем эмулятор терминала.

# Переходим в учётную запись рута:
sudo su

# Загрузим необходмые скрипты:
scripturl='https://raw.githubusercontent.com/S0u1b0y/install/in/my'
curl -o /pacman-prepare "$scripturl/pacman-prepare"
curl -o /arch-btrfs "$scripturl/arch-btrfs"
curl -o /arch-ext4 "$scripturl/arch-ext4"
curl -o /arch-bios "$scripturl/arch-bios"

# ***

## Подготовка Pacman и репозиториев ##

# Для установки Archlinux:
sh /pacman-prepare archlinux

# Для установки Manjaro:
sh /pacman-prepare manjaro

#-----------------------------------------------------------------

### Установка ###

## Btrfs ##
# Передаваемые скрипту параметры:
# 1й - размер файла подкачки в гигабайтах
# 2й - ядро для Archlinux (linux - стандартное ядро, linux-lts - LTS-ядро, linux-zen - Zen-ядро),
#      ядро для Manjaro (linux515 - стандартное ядро, linux510 - LTS-ядро),
# 3й - имя пользователя
# 4й - имя компьютера в сети
# 5й - Устанавливаемое окружение рабочего стола (Возможные варианты: xfce, plasma, gnome), если оставить пустым или ввести неправильное значение, то установиться только консоль.

# VirtualBox
sh /arch-btrfs 2G linux user virt gnome

# Main
sh /arch-btrfs 8G linux soulboy main gnome

# ***

## Ext4 ##
# Передаваемые скрипту параметры:
# 1й - размер root-раздела для ext4 в гигабайтах, под раздел home - всё остальное пространство
# 2й - размер файла подкачки в гигабайтах
# 3й - ядро для Archlinux (linux - стандартное ядро, linux-lts - LTS-ядро, linux-zen - Zen-ядро),
#      ядро для Manjaro (linux515 - стандартное ядро, linux510 - LTS-ядро),
# 4й - Режим установки: normal - обычная установка с удалением всего содержимого диска, safe - установка с сохранением домашнего раздела.
# 5й - имя пользователя
# 6й - имя компьютера в сети
# 7й - Устанавливаемое окружение рабочего стола (Возможные варианты: xfce, plasma, gnome), если оставить пустым или ввести неправильное значение, то установиться только консоль.

# VirtualBox
sh /arch-ext4 20G 2G linux normal user virt gnome

# Main
sh /arch-ext4 40G 8G linux safe soulboy main gnome

#-----------------------------------------------------------------

#Если, на компьютере, есть MS Windows, то установим локальное время:
hwclock --systohc --localtime && date

#Если, на компьютере, только GNU/Linux, то установим время по UTC:
hwclock --systohc --utc && date

#-----------------------------------------------------------------

# Завершаем установку и перезагружаемся:
reboot

#-----------------------------------------------------------------
                #### После перезагрузки ####
#-----------------------------------------------------------------

# Настройку Zsh см. в файле https://raw.githubusercontent.com/S0u1b0y/install/in/arch-zsh

# yay
cd /tmp && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin
makepkg --noconfirm -si

# Необходимые утилиты и оформление
yay --noconfirm -S pamac-aur papirus-icon-theme qogir-icon-theme matcha-gtk-theme \
    ttf-meslo-nerd-font-powerlevel10k qt5ct qt6-base adwaita-qt
echo 'export QT_QPA_PLATFORMTHEME=qt5ct' | sudo tee -a /etc/profile

#-----------------------------------------------------------------

# Автозагрузка GDM:
echo -e "[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=${USER}" | sudo tee -a /etc/gdm/custom.conf

#-----------------------------------------------------------------

## Программы для VirualBox ##

yay --noconfirm -S ananicy nohang librewolf-bin xdg-utils eog evince foliate file-roller \
    gnome-calculator
sudo systemctl enable --now ananicy nohang
autoremove

#-----------------------------------------------------------------

## Программы ##

# Дополнительный софт:
yay --noconfirm -S eog evince foliate file-roller gnome-calculator deadbeef \
    mediainfo mkvtoolnix-gui cherrytree

# Утилиты для контроля за использованием памяти:
yay --noconfirm -S ananicy nohang
sudo systemctl enable --now ananicy nohang

# Браузеры:
yay --noconfirm -S firefox firefox-i18n-ru librewolf-bin chromium

# Torrent:
sudo pacman --noconfirm -S transmission-remote-gtk qbittorrent

# MPV
sudo pacman --noconfirm -S mpv youtube-dl
# Настроки MPV:
mkdir ~/.config/mpv
cp /usr/share/doc/mpv/mpv.conf ~/.config/mpv/mpv.conf
cp /usr/share/doc/mpv/input.conf ~/.config/mpv/input.conf
echo -e "\n#### My Settings ####\n
save-position-on-quit
no-border
\nvolume=40
geometry=40%
\n# Youtube
ytdl-format='bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best[height<=?1080][fps<=60]'
\n#-----------------------------------------------------------------
\n$(cat ${HOME}/.config/mpv/mpv.conf)" > ~/.config/mpv/mpv.conf
echo -e "\n#### Mouse ####
MBTN_LEFT     ignore
MBTN_LEFT_DBL cycle fullscreen
MBTN_RIGHT    cycle pause
MBTN_BACK     playlist-prev
MBTN_FORWARD  playlist-next
MBTN_MID      cycle ontop
WHEEL_UP      add volume  5
WHEEL_DOWN    add volume -5
\n#### Keyboard ####
RIGHT         seek  5
LEFT          seek -5
UP            add volume  5
DOWN          add volume -5
\n#-----------------------------------------------------------------
\n$(cat ${HOME}/.config/mpv/input.conf)" > ~/.config/mpv/input.conf

# Code OSS (free VSCode):
yay --noconfirm -S code
# Сменить язык на русский:
# Ctrl+Shift+P -> вводим - Configure Display Language -> Меняем на Русский
# Настроки:
echo -e '{
    "workbench.colorTheme": "Default Dark+",
    "window.menuBarVisibility": "compact",
    "workbench.activityBar.visible": false,
    "security.workspace.trust.untrustedFiles": "open",
    "editor.mouseWheelScrollSensitivity": 2,
    "editor.renderWhitespace": "none",
    "editor.wordWrap": "on",
    "editor.fontSize": 12,
    "editor.dragAndDrop": false,
    "editor.renderLineHighlight": "none"
    "editor.guides.indentation": false
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "terminal.integrated.fontSize": 12
}' > ~/.config/Code - OSS/User/settings.json

# Plank:
sudo pacman --noconfirm -S plank

# Yandex Disk:
yay --noconfirm -S yandex-disk && yandex-disk setup

# gnome-disk-utility - Управление дисками.
sudo pacman --noconfirm -S gnome-disk-utility

# gnome-system-monitor - Мониторинг системы.
sudo pacman --noconfirm -S gnome-system-monitor

# Если нужна поддержка принтера, то ставим:
pacman --noconfirm -S cups cups-pdf system-config-printer
sudo systemctl enable --now cups.service

# Управление сетевыми соединениями (опционально):
sudo pacman --noconfirm -S networkmanager plasma-nm
sudo systemctl enable --now NetworkManager

# Bluetooth (опционально):
sudo pacman --noconfirm -S blueman
sudo systemctl enable --now bluetooth

#-----------------------------------------------------------------

## Игры ##

# Steam:
sudo pacman --noconfirm -S steam

# PortProton (https://portwine-linux.ru/port-proton-linux):
sudo pacman --noconfirm -S gamemode lib32-gamemode icoutils zenity bubblewrap zstd cabextract tar
wget -c 'https://github.com/Castro-Fidel/PortWINE/raw/master/portwine_install_script/PortProton-97'
sh PortProton-97

# Настройка Proton в Steam-клиенте на Linux: В меню (вверху слева) нажимаем: Steam->Настройки,
# выбираем раздел Steam Play (в самом низу) и там ставим галочку "Включить Steam Play для других продуктов",
# жмем ОК. Все Proton включён, можно пытаться запускать Windows-игры.

# Minecraft:
yay --noconfirm -S multimc jre-openjdk jre8-openjdk
sudo archlinux-java set java-17-openjdk
archlinux-java status

#-----------------------------------------------------------------

## Виртуализация ##

# VirtualBox стандартное ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-modules-arch
# VirtualBox LTS-ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-dkms

# KVM (Qemu):
sudo pacman --noconfirm -S virt-manager bridge-utils dnsmasq dmidecode ebtables iptables \
    openbsd-netcat qemu qemu-arch-extra qemu-guest-agent ovmf vde2
sudo systemctl enable --now libvirtd dnsmasq
sudo gpasswd -a $(whoami) kvm libvirt && newgrp libvirt
sudo sed -i 's/^#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/' /etc/libvirt/libvirtd.conf
sudo sed -i 's/^#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/' /etc/libvirt/libvirtd.conf
sudo systemctl restart libvirtd.service
