#!/bin/bash

#### Установка Arch XFCE ####

### Подготовка ###

# Скачиваем образ Manjaro Minimal для установки Manjaro или Archlinux - https://manjaro.org/downloads/official/xfce/
# Или скачиваем образ EndeavourOS для установки только Archlinux - https://endeavouros.com/latest-release/
# Записываем образ на флешку програмой Ventoy - https://github.com/ventoy/Ventoy/releases
# Загружаемся с записанного образа

# Переходим в учётную запись рута:
sudo su

## Настройка Pacman и репозиториев ##
# Передаваемые скрипту параметры:
# 1й - Устанавливаемая система, значения: archlinux или manjaro.

# Для установки Archlinux:
curl -O "https://raw.githubusercontent.com/S0u1b0y/install/in/my/pacman-prepare-my"
sh pacman-prepare archlinux

# Для установки Manjaro:
curl -O "https://raw.githubusercontent.com/S0u1b0y/install/in/my/pacman-prepare-my"
sh pacman-prepare manjaro

#-----------------------------------------------------------------

### Установка ###
# Разметка, форматирование диска и установка базовой системы.
# Ядра: linux - стандартное ядро, linux-lts - LTS-ядро, linux-zen - Zen-ядро

## Btrfs ##

# VirtualBox
curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-base-btrfs'
sh arch-base-btrfs 2G linux

# Main
curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-base-btrfs'
sh arch-base-btrfs 8G linux

# ***

## Ext4 ##

# VirtualBox
curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-base-ext4'
sh arch-base-ext4 40G 2G linux

# Main
curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-base-ext4'
sh arch-base-ext4 40G 8G linux

#-----------------------------------------------------------------

## Чрутимся:
# Если ставим из Manjaro
manjaro-chroot /mnt
# Если ставим из EndeavourOS или Archlinux
arch-chroot /mnt

#-----------------------------------------------------------------

## Установка основной системы ##

# VirtualBox
cd /tmp && curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-system-bios'
sh arch-system-bios user virt

# Main
cd /tmp && curl -O 'https://raw.githubusercontent.com/S0u1b0y/install/in/my/arch-system-bios'
sh arch-system-bios soulboy main

#-----------------------------------------------------------------

#Если, на компьютере, есть MS Windows, то установим локальное время:
hwclock --systohc --localtime && date

#Если, на компьютере, только GNU/Linux, то установим время по UTC:
hwclock --systohc --utc && date

#-----------------------------------------------------------------

## Статический IP для VirualBox ##
cp -n /etc/dhcpcd.conf /etc/dhcpcd.conf.bak
echo -e 'interface enp0s3
static ip_address=192.168.0.50/24
static routers=192.168.0.100
static domain_name_servers=192.168.0.100' > /etc/dhcpcd.conf

#-----------------------------------------------------------------

## Установка XFCE ##

pacman --noconfirm -S xorg-server xfce4 lxdm pavucontrol xed tilix thunar-archive-plugin \
    xfce4-xkb-plugin xfce4-pulseaudio-plugin xfce4-clipman-plugin xfce4-whiskermenu-plugin \
    xfce4-weather-plugin gnome-disk-utility
systemctl enable lxdm.service
pacman --noconfirm -R xfce4-terminal

#-----------------------------------------------------------------

# Завершаем установку, выходим (Ctrl+D) и перезагружаемся:
reboot

#-----------------------------------------------------------------
#-----------------------------------------------------------------

#### После перезагрузки ####

# Установку и настройку Zsh см. в файле https://raw.githubusercontent.com/S0u1b0y/install/in/arch-zsh

echo -e '\n#Для терминала Tilix
if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi

#### Aliases ####

# Переопеделение Pacman для установки и удаления без подтверждения:
alias spac="sudo pacman --noconfirm"

# Удаление неиспользуемых пакетов (Если нечего удалять, вылезет "ошибка: аргумент "-" указан с пустым stdin", это нормально).
alias autoremove="sudo pacman --noconfirm -Qtdq | sudo pacman --noconfirm -Rns -"
alias фгещкуьщму="sudo pacman --noconfirm -Qtdq | sudo pacman --noconfirm -Rns -"

# Быстрое обновление (pup - Pacman UPdate)
alias pup="sudo pacman -Syu"
alias згз="sudo pacman -Syu"

# Пинг делает только 5 запросов.
alias ping="ping -c 5"' >> ~/.bashrc
source ~/.bashrc
echo 'blacklist pcspkr' | sudo tee /etc/modprobe.d/nobeep.conf
echo 'vm.swappiness=10' | sudo tee /etc/sysctl.d/99-swappiness.conf
sudo sed -i 's/#DefaultTimeoutStopSec=90s/DefaultTimeoutStopSec=10s/' /etc/systemd/system.conf
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=50M/' /etc/systemd/journald.conf
sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo pacman --noconfirm -S xdg-user-dirs && LC_ALL=C xdg-user-dirs-update --force
cd /tmp && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg --noconfirm -si
yay --noconfirm -S pamac-aur menulibre papirus-icon-theme qogir-icon-theme matcha-gtk-theme \
    ttf-meslo-nerd-font-powerlevel10k qt5ct qt6-base adwaita-qt
echo 'export QT_QPA_PLATFORMTHEME=qt5ct' | sudo tee -a /etc/profile

# Автологин LXDM:
#echo -e "[base]\nautologin=${USER}" | sudo tee -a /etc/lxdm/lxdm.conf

#-----------------------------------------------------------------

## Программы для VirualBox ##

yay --noconfirm -S ananicy nohang librewolf-bin
sudo systemctl enable --now ananicy nohang
autoremove

#-----------------------------------------------------------------

## Программы для Main ##

# Браузеры:
yay --noconfirm -S firefox firefox-i18n-ru librewolf-bin chromium

# Code OSS (free Visual Studio Code):
yay --noconfirm -S code
# Мои настройки:
mouseWheelScrollSensitivity - 2
editor.renderWhitespace - none
editor.wordWrap - On
editor.fontSize - 12
editor.dragAndDrop - false
# Сменить язык на русский
Ctrl-Shift-P -> Configure Display Language -> Меняем на Русский

# Дополнительный софт:
yay --noconfirm -S xarchiver galculator xed xviewer xviewer-plugins xreader foliate \
    gnome-disk-utility deadbeef mpv
yay --noconfirm -S ananicy nohang mediainfo mkvtoolnix-gui cherrytree
sudo systemctl enable --now ananicy nohang

# Plank:
# Что бы убрать невидимую полосу - Меню->Настройки->Диспетчер окон (дополнительно)->{Вкладка}Эффекты->Отображать тени под сворачивающимися окнами->Снять галочку.
sudo pacman --noconfirm -S plank

# Yandex Disk:
yay --noconfirm -S yandex-disk && yandex-disk setup

# Мониторинг и разгон для nVidia карт Green With Envy:
yay --noconfirm -S gwe

# gnome-system-monitor - Мониторинг системы.
yay --noconfirm -S gnome-system-monitor

#-----------------------------------------------------------------

## Игры ##

# Steam:
sudo pacman --noconfirm -S steam

# PortProton (https://portwine-linux.ru/port-proton-linux):
sudo pacman --noconfirm -S gamemode lib32-gamemode icoutils zenity bubblewrap zstd cabextract tar
wget -c 'https://github.com/Castro-Fidel/PortWINE/raw/master/portwine_install_script/PortProton-97'
sh PortProton-97

# Настройка Proton в Steam-клиенте на Linux: В меню (вверху слева) нажимаем: Steam->Настройки,
# выбираем раздел Steam Play (в самом низу) и там ставим галочку "Включить Steam Play для других продуктов",
# жмем ОК. Все Proton включён, можно пытаться запускать Windows-игры.

# Minecraft:
yay --noconfirm -S multimc jre-openjdk jre8-openjdk
sudo archlinux-java set java-17-openjdk
archlinux-java status

#-----------------------------------------------------------------

## Виртуализация ##

# VirtualBox стандартное ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-modules-arch
# VirtualBox LTS-ядро:
sudo pacman --noconfirm -S virtualbox virtualbox-ext-vnc virtualbox-host-dkms

# KVM (Qemu):
sudo pacman --noconfirm -S virt-manager bridge-utils dnsmasq dmidecode ebtables iptables \
    openbsd-netcat qemu qemu-arch-extra qemu-guest-agent ovmf vde2
sudo systemctl enable --now libvirtd dnsmasq
sudo gpasswd -a $(whoami) kvm libvirt && newgrp libvirt
sudo sed -i 's/#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/' /etc/libvirt/libvirtd.conf
sudo sed -i 's/#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/' /etc/libvirt/libvirtd.conf
sudo systemctl restart libvirtd.service
